network: MyModel
network_args: 
  classes: 4
  channels: 22
  dim: 32
  pool_size: 50
  pool_stride: 15
  heads: 8
  fc: 4
  depth: 4
  attn_dropout: 0.5
  fc_dropout: 0.5
  cnn_dropout : 0.25


data_path: dataset/bci_iv_2a
out_log: log/bci_iv_2a


device: gpu
nGPU: 0
random_seed: 0

batch_size: 16

epoch: 2000

lr: 0.0002

# Data augmentation
classes: 4
num_segs: 8
